-- Nand Dairy — Disable RLS on all tables to allow custom client authentication
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle DISABLE ROW LEVEL SECURITY;
ALTER TABLE samiti DISABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_samiti_map DISABLE ROW LEVEL SECURITY;
ALTER TABLE milk_entry DISABLE ROW LEVEL SECURITY;
ALTER TABLE milk_test DISABLE ROW LEVEL SECURITY;
ALTER TABLE rate_chart DISABLE ROW LEVEL SECURITY;
ALTER TABLE quality_threshold DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE sync_queue DISABLE ROW LEVEL SECURITY;
